### ISSUE TITLE
Is there a way to obtain data for friendly matches in proclubs mode?

### ISSUE THREAD

**Issue by shuerchoi** [gkimpson/fifa-proclubs-api-v10#1]

**Comment by randomaccountgk** [comment]
Hi Shuerchoi - there isn't any way to get friendlies data at the moment - but if it comes I'll be sure to add it

**Comment by gkimpson** [comment]
Unfortunately there is no way currently to retrieve data for friendly matches, however if this does become a thing i'll be certain to implement it

**Comment by gkimpson** [comment]
Closed as not currently possible to do this
